# Generated by Django 4.2.3 on 2023-11-05 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 15, 13, 6, 605630, tzinfo=datetime.timezone.utc)),
        ),
    ]
