# Generated by Django 4.2.3 on 2023-11-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='is_staff',
        ),
    ]
